version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: app_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring-network

  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'
    command: /bin/sh -c "redis-server --requirepass 123456"
    volumes:
      - cache:/data
    container_name: app_redis  
    networks:
      - monitoring-network

  app:
    build:
      dockerfile: Dockerfile
      context: .
    # volumes:
    #   - .:/go/src/application
    ports:
      - "8080:8080"
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge   
volumes:
  cache:  
